import os
from github import Github
from datetime import datetime


def validate_fix_relevance(fix_description, logs):
    """
    Validate if the fix is relevant to the logs and source code
    
    Args:
        fix_description: The AI-generated fix description
        logs: The original CI/CD logs
        
    Returns:
        tuple: (is_valid, validation_message, confidence_score)
    """
    # Check if fix description contains technical details
    technical_keywords = ['install', 'update', 'fix', 'change', 'modify', 'add', 'remove', 'configure', 'set']
    has_technical_action = any(keyword in fix_description.lower() for keyword in technical_keywords)
    
    # Check if fix references specific files, packages, or configurations
    file_references = ['requirements.txt', 'package.json', 'dockerfile', '.env', 'config', 'yaml', 'yml', 'json']
    has_file_reference = any(ref in fix_description.lower() for ref in file_references)
    
    # Check if fix description is substantial enough
    is_substantial = len(fix_description) > 20
    
    # Calculate confidence score
    confidence_score = 0
    if has_technical_action:
        confidence_score += 30
    if has_file_reference:
        confidence_score += 40
    if is_substantial:
        confidence_score += 30
    
    is_valid = confidence_score >= 50
    
    if is_valid:
        validation_message = f"Fix appears relevant (confidence: {confidence_score}%)"
    else:
        validation_message = f"Fix may not be actionable (confidence: {confidence_score}%)"
    
    return is_valid, validation_message, confidence_score


def create_fix_pr(fix_description, logs=None, branch_type="feature"):
    """
    Create a GitHub PR with an AI-generated fix
    
    Args:
        fix_description: Description of the fix
        logs: Original CI/CD logs for validation (optional)
        branch_type: Type of branch - "feature" or "hotfix" (default: "feature")
    """

    # TEST MODE → Skip PR
    if os.getenv("TEST_MODE") == "true":
        return "PR skipped (TEST MODE)"

    GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
    REPO_NAME = os.getenv("REPO_NAME") or os.getenv("GITHUB_REPO")

    if not GITHUB_TOKEN or not REPO_NAME:
        return "Missing GitHub configuration"

    # Validate fix relevance
    is_valid, validation_message, confidence_score = validate_fix_relevance(fix_description, logs or "")
    
    if not is_valid:
        return f"Validation failed: {validation_message}. Fix may not be actionable."

    try:
        g = Github(GITHUB_TOKEN)
        repo = g.get_repo(REPO_NAME)

        print(f"Connected to repo: {repo.full_name}")

        base_branch = repo.default_branch
        
        # Generate descriptive branch name based on type
        timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
        if branch_type == "hotfix":
            branch_prefix = "hotfix"
            pr_title = "Hotfix: GeminiGuard Auto Fix"
        else:
            branch_prefix = "feature"
            pr_title = "Feature: GeminiGuard Auto Fix"
        
        # Create short description slug for branch name
        desc_slug = fix_description[:30].replace(' ', '-').lower().replace('/', '-').replace('\\', '-')
        new_branch = f"{branch_prefix}/ai-fix-{timestamp}-{desc_slug}"

        # Create Branch
        source = repo.get_branch(base_branch)
        repo.create_git_ref(
            ref=f"refs/heads/{new_branch}",
            sha=source.commit.sha
        )

        # Create more meaningful fix documentation
        file_path = "AI_FIX_NOTES.md"
        content = f"""# AI-Generated Fix Notes

## Fix Description
{fix_description}

## Validation Information
- **Validation Status:** {validation_message}
- **Confidence Score:** {confidence_score}%
- **Branch Type:** {branch_type}
- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Implementation Notes
This fix was automatically generated by GeminiGuard based on CI/CD log analysis.
Please review and implement the suggested changes manually.

## Related Logs
```
{logs[:500] if logs else "No logs provided"}
```

---
*Automatically created by GeminiGuard CI/CD Analyzer*
"""

        try:
            contents = repo.get_contents(file_path, ref=new_branch)
            repo.update_file(
                path=contents.path,
                message="Update AI fix notes",
                content=content,
                sha=contents.sha,
                branch=new_branch
            )
            print("Updated existing fix notes")
        except Exception:
            repo.create_file(
                path=file_path,
                message="Add AI fix notes",
                content=content,
                branch=new_branch
            )
            print("Created new fix notes")

        # Create Pull Request with enhanced information
        pr = repo.create_pull(
            title=pr_title,
            body=f"""## AI-Generated Fix

### Validation Results
- **Status:** {validation_message}
- **Confidence:** {confidence_score}%
- **Branch Type:** {branch_type}

### Proposed Fix
{fix_description}

### Implementation Required
This PR contains documentation for the AI-suggested fix. Please:
1. Review the fix notes in `AI_FIX_NOTES.md`
2. Implement the suggested changes manually
3. Test the changes
4. Update this PR with actual code modifications

### Context
- **Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
- **Analyzer:** GeminiGuard CI/CD
- **Branch:** `{new_branch}`

---
*Please review and implement the fix manually. This PR provides documentation and validation for the AI-suggested solution.*
""",
            head=new_branch,
            base=base_branch
        )

        return f"PR Created: {pr.html_url} (Validation: {validation_message})"

    except Exception as e:
        return f"GitHub Error: {str(e)}"